; [download]
; path = /downloads/
; label = Download

; [docs]
; path = /docs/
; label = Documentation

; [poweredby]
; path = /showcase/
; label = Showcase

; [plugins]
; path = /plugins/
; label = Plugins

; [gallery]
; path = /gallery/
; label = Gallery

# [themes]
# path = /themes/
# label = Themes

; [community]
; path = /community/
; label = Community

; [blog]
; path = /blog/
; label = Blog

[program]
path = /program/
label = 18🈲

[web]
path = /web/
label = Web

[links]
path = /links/
label = 友链

[quotes]
path = /quotes/
label = 语录

[about]
path = /about/
label = 关于我

[update]
path = /update/
label = 更新