[download]
path = /downloads/
label = Download

[docs]
path = /docs/
label = Documentation

[poweredby]
path = /showcase/
label = Showcase

[plugins]
path = /plugins/
label = Plugins

[gallery]
path = /gallery/
label = Gallery

# [themes]
# path = /themes/
# label = Themes

[community]
path = /community/
label = Community

[blog]
path = /blog/
label = Blog

[program]
path = /program/
label = Program

[about]
path = /about/
label = About

[web]
path = /web/
label = Web